DROP TABLE t_insightia_anuncio CASCADE CONSTRAINTS;

DROP TABLE t_insightia_comando CASCADE CONSTRAINTS;

DROP TABLE t_insightia_insight CASCADE CONSTRAINTS;

DROP TABLE t_insightia_transacao CASCADE CONSTRAINTS;

DROP TABLE t_insightia_usuario CASCADE CONSTRAINTS;

DROP TABLE t_insightia_auditoria CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_INSIGHTIA_USUARIO;

DROP SEQUENCE SQ_INSIGHTIA_ANUNCIO;

DROP SEQUENCE SQ_INSIGHTIA_TRANSACAO;

DROP SEQUENCE SQ_INSIGHTIA_COMANDO;

DROP SEQUENCE SQ_INSIGHTIA_INSIGHT;

DROP SEQUENCE SQ_INSIGHTIA_AUDITORIA;
